### ISSUE TITLE
Send PR to nodejs repo?

### ISSUE THREAD

**Issue by TooTallNate** [vdeturckheim/async-module#1]
Hey pretty cool little hack haha. Since it's so simple, it might be worth getting a conversation going about merging it upstream? I for one am sick of writing little test scripts containing:

```js
async function main() {
  // code...
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
```

**Comment by vdeturckheim** [comment]
Thanks @TooTallNate !

I'll add error handling and REPL support in the future. But I still don't believe that breaking the ES syntax is a good idea ^^
